version: '3'

services:  
    php: 
        image: php:7.2-fpm
        ports:
            - '8000:9000'
        build: 
            context: ./docker
            dockerfile: php.Dockerfile
        restart: always
        container_name: ${APP_NAME:?err}-php
        volumes: 
            - ./app:/var/www/html
    
    nginx: 
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        restart: always
        ports: 
            - '80:80'
            - '443:443'
        links:
            - 'php'
        depends_on: 
            - 'php'
        volumes: 
            - ./app:/var/www/html
            - ./config/nginx:/etc/nginx/conf.d

    mysql: 
        image: mysql:5.7
        container_name: ${APP_NAME:?err}-mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?err}
            MYSQL_DATABASE: ${DB_NAME}
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: Recipe-phpmyadmin
        restart: always
        depends_on:
            - mysql
        ports:
            - '8080:80'
        links: 
            - mysql
        environment:
            - PMA_HOST=${APP_NAME:?err}-mysql
            - PMA_PORT=3306
        
