version: '3'
services:  
    php: 
        image: php:7.2-fpm
        ports:
            - '9000:9000'
        build: 
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes: 
            - ./app:/var/www/html
    
    nginx: 
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx        
        ports: 
            - '80:80'
            - '443:443'
        links:
            - 'php'
        depends_on: 
            - 'php'
        volumes: 
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    mysql: 
        image: mysql:5.7
        container_name: ${APP_NAME:?err}-mysql
        restart: on-failure
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?err}
            MYSQL_DATABASE: ${DB_NAME:?${APP_NAME}}
        volumes: 
            -${PWD}

        
