version: '3'

services:  
    php: 
        ports:
            - '8000:9000'
        build: 
            context: "./docker"
            dockerfile: "php.Dockerfile"
        restart: always
        container_name: php
        links:
            - mysql
        volumes: 
            - ./app:/var/www/html

    nginx: 
        image: nginx:latest
        container_name: nginx
        restart: always
        ports: 
            - '80:80'
            - '443:443'
        links:
            - 'php'
        depends_on: 
            - 'php'
        volumes: 
            - ./app:/var/www/html
            - ./config/nginx:/etc/nginx/conf.d

    mysql: 
        image: mysql:5.7
        container_name: mysql
        restart: always
        volumes:
            - ./db_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?err}
            MYSQL_DATABASE: ${DB_NAME}
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always           
        depends_on:
            - mysql
        ports:
            - '8080:80'
        links: 
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 8081:9000
            - 9000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data       
volumes: 
    db-data:
    portainer_data: